name: Build Nix Binary and Create Bash Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nix
      run: |
        sh <(curl -L https://nixos.org/nix/install) --daemon
        source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

    - name: Configure Nix for experimental features and trusted users
      run: |
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        echo 'trusted-users = root runner' | sudo tee -a /etc/nix/nix.conf
        sudo pkill nix-daemon
        sudo systemctl start nix-daemon

    - name: Build LNbits using Nix
      run: |
        source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        git clone https://github.com/arcbtc/lnbits.git
        cd lnbits
        nix build
        mkdir -p $GITHUB_WORKSPACE/data

    - name: Create run_nix_lnbits.sh
      run: |
        echo "#!/bin/bash" > $GITHUB_WORKSPACE/run_nix_lnbits.sh
        echo "LNBITS_ADMIN_UI=true" >> $GITHUB_WORKSPACE/run_nix_lnbits.sh
        echo "mkdir -p data" >> $GITHUB_WORKSPACE/run_nix_lnbits.sh
        echo "\$(dirname \"\$0\")/lnbits/result/bin/lnbits --port 9000 --host 0.0.0.0" >> $GITHUB_WORKSPACE/run_nix_lnbits.sh
        chmod +x $GITHUB_WORKSPACE/run_nix_lnbits.sh

    - name: Ensure script is in root
      run: ls -la $GITHUB_WORKSPACE/
